version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domainkit_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    command:
      - -webKey=${WEB_KEY}
      - -appKey=${APP_KEY}